# @package _global_
checkpoint: null

tensorboard: true
auto_cpu_if_no_gpu: true
device: cuda:2
mixed_precision: false
save: true
eval_freq: 1000
eval_iters: 100

hparams:
  batch_size: 128
  epochs: 10

k: 10
feed_layers: null
train_projector: true
use_ema: false
diffae_ckpt_path: /projects/deepdevpath2/Saranga/diffae/checkpoints/ffhq128_w_newclassifier2/epoch_checkpoints/epoch=719-step=196403.ckpt